### ISSUE TITLE
Algorithm for Creating Branch Thickness

### ISSUE THREAD

**Issue by tshur** [tshur/IEAC-bronco-tree#7]
After reading sections of the paper about the space colonization algorithm, I realized that there is a more realistic way to choose the thickness of the branches. We can (potentially continually) start from the tips of the twigs and work our way down to the trunk, increasing the thickness each time two branches merge. We could potentially do this while we draw the tree in order to save some computation time (i.e., we could draw the tree leaf to base and employ this calculation). I think this would also have the added effect of causing the branches of the tree to grow in thickness over time.

Here is an excerpt from the research paper:

> Calculation begins with the assumption that all branch tips have
> the same initial radius r<sub>0</sub>, and proceeds basipetally, from the
> branch tips toward the tree base. If branches of radii r<sub>1</sub> and
> r<sub>2</sub> meet in a branching point, the radius r of the supporting
> branch is found using the formula
> r<sup>n</sup> = r<sub>1</sub><sup>n</sup> +r<sub>2</sub><sup>n</sup>
> where n is a parameter of the method (usually between
> 2 and 3. [Reference Link](http://algorithmicbotany.org/papers/colonization.egwnp2007.pdf)

**Comment by IsaacSCU** [comment]
How would we do this in an interactive sense? wouldn't the user try to grow from the trunk out? or would it re-compute thickness after a user growth?

**Comment by tshur** [comment]
I believe the idea would be to still visually grow the tree from the trunk out, but determine the thickness of each branch by starting at the twigs and adding thickness as the branches formed together.

For example, suppose a full tree was created with a thick trunk, and then a user created a new leaf right next to the base of the tree. This process would result in a thin twig being extended from the trunk. Also, this would increase the thickness of the trunk slightly.

**Comment by tshur** [comment]
Update on working with this. Figured out how to make the method work. Currently having trouble when a branch straddles two nodes perfectly. This branch grows forever (but no movement) towards these two nodes which are pulling the branch equally. This causes the problem with many branches being created without any movement towards the leaves. I am creating an issue now to fix this problem.

**Comment by tshur** [comment]
Working solution for this feature is in the tree-drawing branch.
