### ISSUE TITLE
Problem when branch straddles two nodes perfectly

### ISSUE THREAD

**Issue by tshur** [tshur/IEAC-bronco-tree#9]
Originally, I thought this wouldn't be a problem as these nodes would simply disappear over time. However, these nodes are actually causing the neighboring branch to keep producing more and more branches (which don't even move closer to the leaves). I propose to fix this by adding some sort of randomness in the pull strength by each node to cause the branches to move one way or another.

**Comment by tshur** [comment]
Temporarily solved by introducing some randomness to the system, but could be better implemented to insure immediate problem resolution.

**Comment by jcallin** [comment]
In the pull request, you can type "fixes # " followed by the issue number to reference this!
